services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    # The container name is customizable via the CONTAINER_NAME env var, defaulting to cabinet-advice-web
    container_name: ${CONTAINER_NAME:-cabinet-advice-web}
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - webproxy

networks:
  webproxy:
    external: true
